Repository fs-04-Moving/4-moving-team-fe1, pull requests merged in 2025-04, with the labels that each got.

#22 [정진호] refactor: Chip에 대한 타입 생성 및 컴포넌트 분리
  app/(providers)/(root)/test/jjh/page.tsx
  components/atoms/ChipEstimateRequestStatus.tsx
  components/atoms/ChipEstimateStatus.tsx
  components/atoms/ChipMoveType.tsx
  components/atoms/ChipMovingType.tsx
  types/move.type.ts
Labels: refactor

#17 [김주영] feat: Chip 주소컴포넌트 구현
  app/(providers)/(root)/test/kjy/page.tsx
  components/atoms/ChipBubbleTypeBox.tsx
  components/molecules/RegionDisplay.tsx
  components/molecules/RegionSelector.tsx
  types/entities/region.entity.ts
Labels: feat

#26 [조형민] 로그인/회원가입 API 구현, Button/Dropdown 컴포넌트 추가 등
  api/users/users.api.ts
  app/(providers)/(root)/auth/log-in/page.tsx
  app/(providers)/(root)/auth/sign-up/page.tsx
  app/globals.css
  assets/images/ic-chevron-down-black.svg
  assets/images/ic-chevron-down.svg
  assets/images/ic-writing.svg
  components/atoms/ButtonOutlined.tsx
  components/atoms/ButtonSolid.tsx
  components/atoms/ChatBubbleTextLeft.tsx
  components/atoms/ChatBubbleTextRight.tsx
  components/atoms/DropdownButton.tsx
  components/atoms/DropdownList.tsx
  components/atoms/Input.tsx
  components/atoms/InputAddress.tsx
  components/atoms/LabelInput.tsx
  components/atoms/TempAuthRegistButton.tsx
  components/molecules/ChatBubbleAddress.tsx
  components/molecules/Dropdown.tsx
  components/organisms/FormLogin.tsx
  components/organisms/FormSignUp.tsx
  components/templates/TemplateLogIn.tsx
  components/templates/TemplateSignUp.tsx
  constants/formValidation.ts
  constants/index.ts
  types/dtos/estimate.dto.ts
  types/dtos/user.dto.ts
Labels: feat

#20 [김희주]feat: Tab-button, 헤더 atom
  app/(providers)/(root)/test/khju/page.tsx
  assets/images/ic-alarm.svg
  assets/images/ic-menu.svg
  assets/images/ic-profile.svg
  components/atoms/CloseButton.tsx
  components/atoms/IconButton.tsx
  components/atoms/NavigationText.tsx
  components/atoms/TabButton.tsx
  components/molecules/GNBMenu.tsx
Labels: feat

#48 [조형민] 데이터 타입 수정/추가
  api/users/users.api.ts
  components/organisms/FormLogin.tsx
  components/organisms/FormSignUp.tsx
  types/dtos/auth.dto.ts
  types/dtos/estimate.dto.ts
  types/dtos/estimateRequest.dto.ts
  types/dtos/profile.dto.ts
  types/dtos/review.dto.ts
  types/dtos/user.dto.ts
  types/entities/estimate.entity.ts
  types/entities/estimateRequest.entity.ts
  types/entities/user.entity.ts
Labels: fix, feat

#50 [조형민] 데이터 타입 수정, 컴포넌트 추가
  app/(providers)/(root)/test/jhm/page.tsx
  assets/images/ic-clip.svg
  assets/images/ic-facebook-f.svg
  assets/images/ic-filter-off.svg
  assets/images/ic-filter.svg
  assets/images/ic-kakao-bubble.svg
  assets/images/ic-like.svg
  components/atoms/ButtonClipOutlined.tsx
  components/atoms/ButtonLikeOutlined.tsx
  components/atoms/ButtonPopFilter.tsx
  components/atoms/ButtonShareFacebook.tsx
  components/atoms/ButtonShareKakao.tsx
  components/molecules/ChatBubbleAddress.tsx
  components/organisms/FormLogin.tsx
  components/organisms/FormSignUp.tsx
  components/templates/TemplateLogIn.tsx
  components/templates/TemplateSignUp.tsx
  libs/tanstack-query/index.tsx
  types/dtos/estimate.dto.ts
  types/dtos/estimateRequest.dto.ts
  types/dtos/review.dto.ts
  types/dtos/user.dto.ts
  types/entities/estimate.entity.ts
Labels: fix, feat

#59 [구은모] chore: 별점 리뷰 차트 자잘한 수정
  app/(providers)/(root)/test/kem/page.tsx
  assets/images/ic-check-box-active-round.svg
  assets/images/ic-check-box-active-square.svg
  assets/images/ic-check-box-default-round.svg
  assets/images/ic-check-box-default-square.svg
  components/atoms/ChartAverageReview.tsx
  components/atoms/IconEmptyStar.tsx
  components/atoms/IconFullStar.tsx
  components/atoms/ProgressBarStarRating.tsx
  components/atoms/StarRatingProgressBar.jsx
  components/atoms/StarRatingProgressBar.tsx
  components/molecules/ButtonStarRating.tsx
  components/organisms/ChartStarRatingReview.tsx
  components/organisms/StarRatingCard.tsx
Labels: chore

#36 [김희주] Header component 구현
  app/(providers)/(root)/test/khju/page.tsx
  assets/images/logo-only-icon.svg
  components/atoms/CloseButton.tsx
  components/atoms/HeaderTab.tsx
  components/atoms/IconButton.tsx
  components/atoms/NavigationText.tsx
  components/molecules/GNBMenu.tsx
  components/organisms/HeaderDefault.tsx
  components/organisms/HeaderDefaultTech.tsx
  components/organisms/HeaderLanding.tsx
Labels: feat

#65 [김희주] feat: datepicker 구현
  app/(providers)/(root)/test/khju/datepicker/page.tsx
  assets/images/chevron-left.svg
  assets/images/chevron-right.svg
  components/atoms/datepicker/index.tsx
  components/atoms/datepicker/style.css
  package-lock.json
  package.json
Labels: feat

#62 [구은모] feature:프로그레스바 컴포넌트 구현/별점 사이즈프롭스 추가
  app/(providers)/(root)/test/kem/page.tsx
  components/molecules/ButtonStarRating.tsx
  components/molecules/ProgressBar.tsx
Labels: feat

#68 [조형민] hotfix: 리다이렉트 처리를 middleware로 변경
  app/(providers)/(root)/customer/page.tsx
  app/(providers)/(root)/layout.tsx
  components/molecules/ButtonAuth.tsx
  middleware.ts
Labels: fix

#73 [구은모] 견적요청시 이사선택 체크박스 구현
  app/(providers)/(root)/test/kem/page.tsx
  components/atoms/ButtonCheckBoxOutlined.tsx
  components/atoms/ButtonSolid.tsx
  components/molecules/ButtonCheckBoxRequest.tsx
  components/molecules/ChatBubbleMovingChoice.tsx
  components/molecules/ProgressBar.tsx
  package-lock.json
Labels: feat

#77 [김희주] feat:견적 정보 component 구현 및 datepicker 수정
  app/(providers)/(root)/test/khju/page.tsx
  components/atoms/datepicker/index.tsx
  components/atoms/datepicker/style.css
  components/organisms/EstimateDetailInfo.tsx
Labels: feat, chore

#78 [조형민]리다이렉트 방식 리팩토링, 프로필(등록) 페이지 리팩토링
  app/(providers)/layout.tsx
  components/atoms/ProtectedPageWrapper.tsx
  components/organisms/FormLogin.tsx
  components/organisms/GroupDescriptionInput.tsx
  components/organisms/GroupExperienceInput.tsx
  components/organisms/GroupNicknameInput.tsx
  components/organisms/GroupProfileImageInput.tsx
  components/organisms/GroupRegionSelect.tsx
  components/organisms/GroupServiceTypeSelector.tsx
  components/organisms/GroupSummaryInput.tsx
  components/templates/FormProfileCustomer.tsx
  components/templates/FormProfileWorker.tsx
  components/templates/ProfileCustomer copy.tsx
  components/templates/ProfileCustomer.tsx
  components/templates/ProfileWorker.tsx
  contexts/AuthContext.tsx
  middleware.ts
  utils/getAccessTokenFromRefresh.ts
  utils/getAccessTokenFromRefreshByRefreshToken.ts
  utils/getUserFromRequest.ts
  utils/handlerUtils.ts
  utils/jwtUtils.ts
Labels: fix, feat, refactor

#82 [조형민] Gnb 헤더 구현(미완성), 프로필 등록/로그인/회원가입 리팩토링, 리다이렉트 수정 등
  app/(providers)/(root)/customer/estimates/page.tsx
  app/(providers)/(root)/customer/favorites/page.tsx
  app/(providers)/(root)/find-worker/page.tsx
  app/(providers)/(root)/test/jjh/page.tsx
  app/(providers)/(root)/test/khju/page.tsx
  app/(providers)/(root)/worker/estimates/page.tsx
  components/atoms/CloseButton.tsx
  components/atoms/HeaderTab.tsx
  components/atoms/IconButton.tsx
  components/atoms/LogoIconText.tsx
  components/atoms/NavMenuItem.tsx
  components/molecules/ButtonAuth.tsx
  components/molecules/ChatBubbleMovingChoice.tsx
  components/molecules/GNBMenu.tsx
  components/molecules/NavMenuGnb.tsx
  components/organisms/FormLogin.tsx
  components/organisms/FormSignUp.tsx
  components/organisms/Gnb.tsx
  components/organisms/HeaderDefault.tsx
  components/organisms/HeaderDefaultTech.tsx
  components/organisms/HeaderLanding.tsx
  components/templates/FormProfileCustomer.tsx
  components/templates/FormProfileWorker.tsx
  components/templates/ProfileCustomer copy.tsx
  components/templates/ProfileWorker.tsx
  constants/navMenuItems.ts
  hooks/useCreateProfileMutation.ts
  hooks/useLoginMutation.ts
  hooks/useSignUpMutation.ts
  middleware.ts
  package-lock.json
  utils/handlerUtils.ts
Labels: fix, feat, refactor

#84 [조형민] Gnb 서브 탭 메뉴 구현, 에러메시지 컴포넌트 분리
  app/(providers)/(root)/customer/estimates/pending/page.tsx
  app/(providers)/(root)/customer/estimates/received/page.tsx
  app/(providers)/(root)/customer/reviews/pending/page.tsx
  app/(providers)/(root)/customer/reviews/submitted/page.tsx
  app/(providers)/(root)/test/jhm/page.tsx
  app/(providers)/(root)/worker/estimates/rejected/page.tsx
  app/(providers)/(root)/worker/estimates/sending/page.tsx
  components/atoms/ErrorMessage.tsx
  components/atoms/Input.tsx
  components/atoms/TabMenu.tsx
  components/molecules/SubTab.tsx
  components/organisms/Gnb.tsx
  constants/navMenuItems.ts
Labels: feat, refactor

#90 [조형민] queryClient 생성 방식 변경, '찜한 기사님' 페이지 구현, Gnb 알림/프로필 팝업 메뉴 구현 등
  app/(providers)/(root)/customer/favorites/page.tsx
  app/(providers)/layout.tsx
  components/atoms/IconAlarm.tsx
  components/atoms/LoadingSpinner.tsx
  components/atoms/UserAvartar.tsx
  components/molecules/ButtonAuth.tsx
  components/molecules/DropdownNotifications.tsx
  components/molecules/DropdownProfile.tsx
  components/molecules/UserProfile.tsx
  components/organisms/DriverCardInLiked.tsx
  components/organisms/ListFavoriteWorker.tsx
  hooks/useOutsideClick.tsx
  libs/tanstack-query/index.tsx
  types/dtos/user.dto.ts
Labels: fix, feat, refactor

#92 [조형민] Gnb 슬라이드 메뉴 구현, 반응형 조정, navMenuItems 리팩터링, 랜딩페이지 높이 설정 수정
  app/(providers)/(root)/customer/favorites/page.tsx
  app/(providers)/(root)/layout.tsx
  components/atoms/Label.tsx
  components/atoms/SlideMenuItem.tsx
  components/molecules/ButtonAuth.tsx
  components/molecules/DropdownNotifications.tsx
  components/molecules/DropdownProfile.tsx
  components/molecules/GuestMenu.tsx
  components/molecules/LoggedInMenu.tsx
  components/molecules/NavMenuGnb.tsx
  components/molecules/SubTab.tsx
  components/organisms/ButtonAuth.tsx
  components/organisms/Gnb.tsx
  components/organisms/ListFavoriteWorker.tsx
  components/organisms/SlideMenu.tsx
  components/templates/LandingPage.tsx
  constants/navMenuItems.ts
  package-lock.json
  package.json
Labels: fix, feat, refactor

#101 [조형민] 라우팅/로딩 최적화, 랜딩페이지 SSG 적용, not-found/error 페이지 적용
  api/favorite/favorite.api.ts
  app/(landing)/layout.tsx
  app/(landing)/page.tsx
  app/(providers)/(root)/customer/favorites/page.tsx
  app/(providers)/(root)/error.tsx
  app/(providers)/(root)/test/jjh/page.test.tsx
  app/(providers)/(root)/test/kjy/dropdown/page.test.tsx
  app/(providers)/(root)/test/kjy/moving/page.test.tsx
  app/(providers)/(root)/test/kjy/notice/page.test.tsx
  app/(providers)/(root)/test/kjy/page.test.tsx
  app/not-found.tsx
  components/atoms/LoadingComponent.tsx
  components/atoms/ProtectedPageWrapper.tsx
  components/atoms/SkeletonFavoriteList.tsx
  components/molecules/DropdownProfile.tsx
  components/molecules/DropdownService.tsx
  components/molecules/GuestMenuStatic.tsx
  components/molecules/NavMenuGnb.tsx
  components/molecules/NavMenuLanding.tsx
  components/organisms/ButtonAuth.tsx
  components/organisms/ButtonAuthStatic.tsx
  components/organisms/FormLogin.tsx
  components/organisms/GnbLanding.tsx
  components/organisms/ListFavoriteWorker.tsx
  components/organisms/SlideMenu.tsx
  components/organisms/SlideMenuLanding.tsx
  components/organisms/WorkerCardInLiked.tsx
  contexts/AuthContext.tsx
  hooks/useAuthRedirect.ts
  middleware.ts
  package.json
  tsconfig.build.json
  tsconfig.json
  types/dtos/estimateRequest.dto.ts
  types/svg.d.ts
  utils/getUserFromRequestLite.ts
Labels: fix, feat, refactor

#105 [조형민] 이사 유형과 이사 예정일 수정시 기존 선택값을 선택 상태로 표시하는 로직 추가
  components/atoms/datepicker/index.tsx
  components/molecules/ButtonCheckBoxRequest.tsx
  components/molecules/ChatBubbleMovingChoice.tsx
  components/templates/RequestEstimate.tsx
Labels: feat

#118 [김주영] chore: dropdown 지역,서비스타입 반응형수정
  components/atoms/DropdownButton.tsx
  components/atoms/DropdownButtonArea.tsx
  components/atoms/DropdownList.tsx
  components/atoms/DropdownListDoubleRow.tsx
Labels: chore

#130 [조형민] feat: 배포 백엔드 환경에서 작동하도록 설정 추가 외
  api/client.ts
  api/favorite/favorite.api.ts
  api/user/user.api.ts
  app/(providers)/(root)/customer/favorites/page.tsx
  app/(providers)/(root)/customer/page.tsx
  app/(providers)/(root)/customer/profile/edit/page.tsx
  app/(providers)/(root)/find-worker/FindWorkerClient.tsx
  app/(providers)/(root)/test/jjh/page.test.tsx
  app/(providers)/(root)/test/kem/page.tsx
  app/(providers)/(root)/test/khj/page.tsx
  app/(providers)/(root)/test/khju/datepicker/page.tsx
  app/(providers)/(root)/test/khju/page.tsx
  app/(providers)/(root)/test/kjy/dropdown/page.tsx
  app/(providers)/(root)/test/kjy/moving/page.tsx
  app/(providers)/(root)/test/kjy/notice/page.tsx
  app/(providers)/(root)/test/kjy/page.tsx
  app/(providers)/(root)/test/kjy/pagination/page.tsx
  app/(providers)/(root)/test/usm/page.tsx
  app/(providers)/(root)/worker/my-page/page.tsx
  app/(providers)/(root)/worker/profile/edit/page.tsx
  components/atoms/InputAddress.tsx
  components/atoms/Portal.tsx
  components/molecules/ChatBubbleAddress.tsx
  components/molecules/DropdownProfile.tsx
  components/molecules/LoggedInMenu.tsx
  components/molecules/NavMenuGnb.tsx
  components/organisms/ListFavoriteWorker.tsx
  components/templates/GeneralModal.tsx
  components/templates/RequestEstimate.tsx
  constants/env.ts
  constants/navMenuItems.ts
  constants/routes.ts
  libs/tanstack-query/index.tsx
  middleware.ts
  next.config.ts
  package-lock.json
  package.json
  utils/getAreaKeyFromString.ts
  utils/getUserFromRequest.ts
  utils/getUserFromRequestLite.sync.ts
  utils/jwtUtils.ts
Labels: fix, feat

#136 [조형민] 기사님 찾기 페이지 SSR 문제 수정
  api/client.ts
  api/favorite/favorite.api.ts
  api/profiles/profiles.api.ts
  app/(providers)/(root)/find-worker/FindWorkerClient.tsx
  app/(providers)/(root)/find-worker/page.tsx
  app/(providers)/(root)/worker/info/edit/page.tsx
  hooks/useFindWorkerQuery.ts
  middleware.ts
  types/dtos/Worker.dto.ts
Labels: feat

#140 [조형민] 프로필 수정 페이지 구현 완료, 이미지 업로드 규칙 추가 등
  api/client.ts
  api/profiles/profiles.api.ts
  app/(providers)/(root)/customer/profile/edit/page.tsx
  app/(providers)/(root)/worker/profile/edit/page.tsx
  components/atoms/ButtonOutlined.tsx
  components/atoms/ButtonSolid.tsx
  components/molecules/DropdownProfile.tsx
  components/molecules/InputFile.tsx
  components/organisms/GroupProfileImageInput.tsx
  components/organisms/GroupServiceTypeSelector.tsx
  components/templates/FormProfileCustomer.tsx
  components/templates/FormProfileWorker.tsx
  components/templates/ProfileCustomerEdit.tsx
  components/templates/ProfileWorkerEdit.tsx
  constants/index.ts
  contexts/AuthContext.tsx
  utils/auth.helper.ts
  utils/handlerUtils.ts
Labels: fix, feat

#143 [조형민] FormLogIn 파일명 import 오류 수정, FavoriteWorkersPage의 prefetch 수정
  app/(providers)/(root)/customer/favorites/page.tsx
  components/templates/TemplateLogIn.tsx
Labels: fix, feat

#161 [조형민] 토큰 모두 쿠키에 탑재, 기사님 마이페이지 구현 등
  api/auth/auth.api.ts
  api/client.ts
  api/favorite/favorite.api.ts
  api/profiles/profiles.api.ts
  api/review/review.api.ts
  api/user/user.api.ts
  app/(providers)/(root)/customer/estimates/pending/[id]/page.tsx
  app/(providers)/(root)/customer/estimates/pending/page.tsx
  app/(providers)/(root)/customer/favorites/page.tsx
  app/(providers)/(root)/customer/info/page.tsx
  app/(providers)/(root)/find-worker/page.tsx
  app/(providers)/(root)/worker/info/page.tsx
  app/(providers)/(root)/worker/my-page/page.tsx
  components/molecules/ButtonAuth.tsx
  components/molecules/LoggedInMenu.tsx
  components/organisms/ChartStarRatingReview.tsx
  components/organisms/GroupRegionSelectWorker.tsx
  components/organisms/WorkerCardInLiked.tsx
  components/organisms/WorkerCardInProfile.tsx
  components/organisms/WorkerCardInWating.tsx
  components/organisms/WorkerMyPage.tsx
  components/templates/FormProfileCustomer.tsx
  components/templates/FormProfileWorker.tsx
  contexts/AuthContext.tsx
  libs/tanstack-query/ssrPrefetchHelper.ts
  tsconfig.json
  types/dtos/user.dto.ts
  types/entities/user.entity.ts
  utils/auth.helper.ts
  utils/getCookieHeader_old.ts
  utils/getUserFromRequest.ts
  utils/getUserFromRequestLite.sync.ts
  utils/getUserFromRequestLite.ts
  utils/handlerUtils.ts
  utils/jwtUtils.ts
Labels: fix, feat

#164 [조형민] cookieHeader 생성/전달 방식 리팩터링 등
  api/auth/auth.api.ts
  api/client.ts
  api/favorite/favorite.api.ts
  api/favorite/favorite.server.api.ts
  api/profiles/profile.server.api.ts
  api/profiles/profiles.api.ts
  api/user/user.api.ts
  api/user/user.server.api.ts
  app/(providers)/(root)/customer/favorites/page.tsx
  utils/getCookieHeader_old.ts
  utils/server/getCookieHeader.server.ts
Labels: perf, refactor
