Repository fs-04-Moving/4-moving-team-fe1, pull requests merged in 2025-05, with the labels that each got.

#172 [조형민] 소셜 로그인 구현
  api/auth/auth.api.ts
  api/user/user.api.ts
  app/(providers)/(root)/auth/callback/page.tsx
  app/(providers)/(root)/auth/log-in/page.tsx
  app/(providers)/(root)/auth/sign-up/page.tsx
  app/(providers)/(root)/error.tsx
  components/atoms/TextArea.tsx
  components/molecules/AuthSocialLogIn.tsx
  components/molecules/Error.tsx
  components/molecules/FooterAuthPage.tsx
  components/molecules/HeaderAuthPage.tsx
  components/organisms/FormLogIn.tsx
  components/organisms/FormSignUp.tsx
  components/templates/TemplateLogIn.tsx
  components/templates/TemplateSignUp.tsx
  constants/routes.ts
  contexts/AuthContext.tsx
  middleware.ts
  utils/attachJosa.ts
  utils/getErrorMessageFromQuery.ts
  utils/oauthUserHelpers.ts
Labels: feat

#175 [조형민] 사용자 세션 하이재킹 공격 방어를 위한 보안용 CSRF 토큰 탑재 - state 검증
  api/auth/auth.api.ts
  app/(providers)/(root)/auth/callback/page.tsx
  utils/oauth/getErrorMessageFromQuery.ts
  utils/oauth/oauthUserHelpers.ts
  utils/oauthUserHelpers.ts
Labels: feat

#180 [조형민] 쿼리 캐시 최적화, Docker 설정, 로그인/회원가입/프로필 화면 개선, build 에러 수정 등
  Dockerfile
  api/auth/auth.api.ts
  app/(providers)/(root)/auth/callback/page.tsx
  app/(providers)/(root)/customer/estimates/pending/page.tsx
  app/(providers)/(root)/customer/estimates/received/page.tsx
  app/(providers)/(root)/customer/estimates/test/page.tsx
  app/(providers)/(root)/customer/favorites/page.tsx
  app/(providers)/(root)/find-worker/page.tsx
  app/(providers)/(root)/worker/_components/LeftMenuInWorkerPage.tsx
  app/(providers)/(root)/worker/estimates/sending/[id]/page.tsx
  app/(providers)/(root)/worker/estimates/sending/page.tsx
  app/(providers)/layout.tsx
  components/molecules/ButtonAuth.tsx
  components/molecules/InputText.tsx
  components/molecules/LoggedInMenu.tsx
  components/organisms/CustomerCardInEstimateModal.tsx
  components/organisms/FormLogIn.tsx
  components/organisms/FormSignUp.tsx
  components/organisms/GroupNicknameInput.tsx
  components/templates/FormProfileCustomer.tsx
  components/templates/FormProfileWorker.tsx
  components/templates/ReceivedRequests.tsx
  constants/formValidation.ts
  contexts/AuthContext.tsx
  docker-compose.fe.yml
  hooks/useCreateProfileMutation.ts
  hooks/useLoginMutation.ts
  hooks/useSignUpMutation.ts
  utils/formatPhoneNumber.ts
  utils/handlerUtils.ts
  utils/oauth/getErrorMessageFromCode.ts
  utils/oauth/getErrorMessageFromQuery.ts
Labels: fix, feat, refactor

#200 [조형민] 찜한 기사님 페이지네이션, 목록이 없을 때 표시할 범용 컴포넌트 추가 등 #191
  api/favorite/favorite.api.ts
  api/favorite/favorite.server.api.ts
  app/(providers)/(root)/customer/favorites/page.tsx
  assets/images/img-empty-review.svg
  components/atoms/PaginationButton.tsx
  components/molecules/AuthSocialLogIn.tsx
  components/molecules/EmptyListMessage.tsx
  components/organisms/ListFavoriteWorker.tsx
  components/organisms/WorkerCardInLiked.tsx
  hooks/useDeviceSize.ts
Labels: fix, feat, refactor

#202 [조형민] fix: getFavoriteWorkers 수정
  api/favorite/favorite.api.ts
Labels: fix

#206 [조형민] 프로필 이미지 수정 시 문제 해결
  api/profiles/profiles.api.ts
  components/molecules/InputFile.tsx
  components/templates/FormProfileCustomer.tsx
Labels: fix

#208 [조형민] 기본 정보 페이지 수정 Feature/207
  components/templates/CustomerInfoEditPage.tsx
  components/templates/CustomerInfoEditTemplate.tsx
  components/templates/FormProfileWorker.tsx
  constants/formValidation.ts
  types/entities/user.entity.ts
Labels: feat

#190 [구은모] 리뷰페이지 구현중 Feature/#151
  api/review/review.api.ts
  api/review/writableReview.api.ts
  api/review/writableReview.server.api.ts
  api/review/writtenReview.api.ts
  app/(providers)/(root)/customer/reviews/pending/PendingReviewsClient.tsx
  app/(providers)/(root)/customer/reviews/pending/page.tsx
  app/(providers)/(root)/customer/reviews/submitted/SubmittedReviewsClient.tsx
  app/(providers)/(root)/customer/reviews/submitted/page.tsx
  app/layout.tsx
  assets/images/img-empty.svg
  components/molecules/EmptyReview.tsx
  components/molecules/EmptyWritableReview.tsx
  components/organisms/ListFavoriteWorker.tsx
  components/organisms/ReviewRegister.tsx
  components/organisms/WorkerCardInCompletedReview.tsx
  components/organisms/WorkerSummaryCardInModal.tsx
  package-lock.json
  package.json
  types/dtos/review.dto.ts
Labels: fix, feat, refactor

#220 [구은모] 코드 리팩토링 및 자잘한 수정 Feature/#212
  api/review/writtenReview.api.ts
  api/review/writtenReview.sever.api.ts
  app/(providers)/(root)/customer/reviews/pending/page.tsx
  app/(providers)/(root)/customer/reviews/submitted/page.tsx
  components/molecules/ButtonStarRating.tsx
  components/templates/PendingReviewsClient.tsx
  components/templates/SubmittedReviewsClient.tsx
  types/dtos/review.dto.ts
Labels: chore, refactor

#238 [조형민] constansts/routes.ts에 기사의 견적 상세 페이지 주소 추가
  constants/routes.ts
  utils/getUserFromRequestLite.ts
Labels: feat

#247 [조형민] 기사의 '마이페이지'내 리뷰 목록 추가
  app/(providers)/(root)/worker/_components/ReviewCardList.tsx
  components/organisms/WorkerMyPage.tsx
Labels: feat

#259 [구은모] 메인 메타데이터, 오픈그래프 추가, 작성한 리뷰 보기 모달 구현 Feature/#258
  app/(providers)/(root)/customer/reviews/pending/page.tsx
  app/(providers)/(root)/customer/reviews/submitted/page.tsx
  app/layout.tsx
  components/organisms/ReviewViewer.tsx
  components/templates/PendingReviewsClient.tsx
  components/templates/SubmittedReviewsClient.tsx
Labels: feat, chore

#262 [조형민] 메인페이지 텍스트 수정, 완료 모달 추가
  components/templates/LandingPage.tsx
  components/templates/RequestEstimate.tsx
  utils/handlerUtils.ts
Labels: fix

#279 [조형민] 로그인/회원가입 오류 발생 시 Swal.fire 모달 구현
  hooks/useLoginMutation.ts
  hooks/useSignUpMutation.ts
Labels: feat

#261 [구은모] chore:페이지네이션 수정 및 스토리북 컴포넌트 생성
  api/review/writtenReview.sever.api.ts
  components/organisms/ChartStarRatingReview.stories.tsx
  components/organisms/ReviewViewer.stories.tsx
  package-lock.json
Labels: chore

#290 [조형민] nav의 subTab 메뉴명 변경, 로그아웃 로직 보강
  components/molecules/ButtonAuth.tsx
  components/molecules/DropdownProfile.tsx
  components/molecules/LoggedInMenu.tsx
  components/molecules/SubTab.tsx
Labels: refactor
